"""GraphQL SDL code generator converting SchemaAST into GraphQL schema definition language.

Outputs type definitions, enums, unions, custom scalars (DateTime, JSON), non-null
and list modifiers, and docstrings using 100% Python standard library.
"""

from __future__ import annotations

from typing import Any, List, Set

from schema_illustrator_studio.models import DataType, EntityAST, FieldAST, SchemaAST


class GraphQLGenerator:
    """Generates GraphQL Schema Definition Language (SDL) from SchemaAST."""

    def __init__(
        self,
        ast: SchemaAST,
        include_docstrings: bool = True,
        generate_inputs: bool = False,
    ) -> None:
        self.ast = ast
        self.include_docstrings = include_docstrings
        self.generate_inputs = generate_inputs

    def generate(self) -> str:
        """Generate GraphQL SDL string."""
        lines: List[str] = []

        # Header
        lines.append(f"# Schema: {self.ast.name or 'Schema'}")
        if self.ast.description:
            lines.append(f"# {self.ast.description}")
        lines.append(f"# Version: {self.ast.version}")
        lines.append("# Generated by schema-illustrator-studio")
        lines.append("")

        # Identify custom scalars needed
        custom_scalars = self._find_required_scalars()
        if custom_scalars:
            for s in sorted(custom_scalars):
                lines.append(f"scalar {s}")
            lines.append("")

        sorted_entities = self.ast.topological_sort()

        for ent_name in sorted_entities:
            entity = self.ast.get_entity(ent_name)
            if not entity:
                continue

            if entity.is_enum:
                lines.extend(self._generate_enum(entity))
            elif entity.is_union:
                lines.extend(self._generate_union(entity))
            else:
                lines.extend(self._generate_type(entity))
                if self.generate_inputs:
                    lines.append("")
                    lines.extend(self._generate_input(entity))

            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _find_required_scalars(self) -> Set[str]:
        """Detect if custom scalars like DateTime, JSON, or UUID are needed."""
        scalars: Set[str] = set()
        for ent in self.ast.entities.values():
            for f in ent.fields:
                if f.type == DataType.DATETIME:
                    scalars.add("DateTime")
                elif f.type in (DataType.JSON, DataType.OBJECT):
                    scalars.add("JSON")
                elif f.type == DataType.BYTES:
                    scalars.add("Bytes")
        return scalars

    def _generate_enum(self, entity: EntityAST) -> List[str]:
        """Generate GraphQL enum."""
        lines: List[str] = []
        if self.include_docstrings and entity.description:
            lines.append(f'"""{entity.description}"""')

        lines.append(f"enum {entity.name} {{")
        for f in entity.fields:
            if self.include_docstrings and f.description:
                lines.append(f'  """{f.description}"""')
            lines.append(f"  {f.name}")
        lines.append("}")
        return lines

    def _generate_union(self, entity: EntityAST) -> List[str]:
        """Generate GraphQL union."""
        lines: List[str] = []
        if self.include_docstrings and entity.description:
            lines.append(f'"""{entity.description}"""')

        types_str = " | ".join(entity.union_types) if entity.union_types else "String"
        lines.append(f"union {entity.name} = {types_str}")
        return lines

    def _generate_type(self, entity: EntityAST) -> List[str]:
        """Generate GraphQL object type or interface."""
        lines: List[str] = []
        if self.include_docstrings and entity.description:
            lines.append(f'"""{entity.description}"""')

        kind = entity.metadata.get("graphql_kind", "type")
        implements_clause = ""
        if entity.implements:
            implements_clause = f" implements {' & '.join(entity.implements)}"

        lines.append(f"{kind} {entity.name}{implements_clause} {{")

        for f in entity.fields:
            if self.include_docstrings and f.description:
                lines.append(f'  """{f.description}"""')

            gql_type = self._map_field_type(f)
            lines.append(f"  {f.name}: {gql_type}")

        lines.append("}")
        return lines

    def _generate_input(self, entity: EntityAST) -> List[str]:
        """Generate GraphQL input type for mutations."""
        lines: List[str] = []
        lines.append(f"input Create{entity.name}Input {{")

        for f in entity.fields:
            if f.is_primary_key:
                continue

            gql_type = self._map_field_type(f)
            lines.append(f"  {f.name}: {gql_type}")

        lines.append("}")
        return lines

    def _map_field_type(self, f: FieldAST) -> str:
        """Map FieldAST to GraphQL type signature."""
        if f.is_array:
            inner = f.array_item_target or self._map_scalar(f.array_item_type or DataType.STRING)
            res = f"[{inner}!]"
            return res if f.is_nullable else f"{res}!"

        if f.target_entity:
            base = f.target_entity
        elif f.enum_values:
            base = "String"
        else:
            base = self._map_scalar(f.type)

        return base if f.is_nullable else f"{base}!"

    def _map_scalar(self, dt: DataType) -> str:
        """Map canonical DataType to GraphQL scalar."""
        mapping = {
            DataType.STRING: "String",
            DataType.INTEGER: "Int",
            DataType.BIGINT: "Int",
            DataType.FLOAT: "Float",
            DataType.DECIMAL: "Float",
            DataType.BOOLEAN: "Boolean",
            DataType.DATETIME: "DateTime",
            DataType.DATE: "String",
            DataType.TIME: "String",
            DataType.UUID: "ID",
            DataType.JSON: "JSON",
            DataType.OBJECT: "JSON",
            DataType.BYTES: "Bytes",
            DataType.ANY: "String",
            DataType.NULL: "String",
        }
        return mapping.get(dt, "String")


def transpile_to_graphql(ast: SchemaAST, **kwargs: Any) -> str:
    """Convenience helper to transpile SchemaAST to GraphQL SDL."""
    gen = GraphQLGenerator(ast, **kwargs)
    return gen.generate()
