"""Pydantic v2 model generator converting SchemaAST into type-safe Python models.

Outputs modern Pydantic v2 BaseModel classes with ConfigDict, Field constraints,
type annotations (datetime, UUID, Enum, List, Optional), docstrings, and forward-ref resolution
using 100% Python standard library.
"""

from __future__ import annotations

import re
from typing import Any, List, Optional

from schema_illustrator_studio.models import (
    ConstraintType,
    DataType,
    EntityAST,
    FieldAST,
    SchemaAST,
)


class PydanticGenerator:
    """Generates Pydantic v2 Python models from SchemaAST."""

    def __init__(
        self,
        ast: SchemaAST,
        include_docstrings: bool = True,
        use_annotated: bool = False,
        generate_orm_mode: bool = True,
    ) -> None:
        self.ast = ast
        self.include_docstrings = include_docstrings
        self.use_annotated = use_annotated
        self.generate_orm_mode = generate_orm_mode

    def generate(self) -> str:
        """Generate complete Python Pydantic v2 module."""
        lines: List[str] = []

        # Module Header
        lines.append('"""Pydantic v2 Data Models.')
        lines.append(f"Schema: {self.ast.name or 'Schema'}")
        if self.ast.description:
            lines.append(f"{self.ast.description}")
        lines.append(f"Version: {self.ast.version}")
        lines.append("Generated by schema-illustrator-studio")
        lines.append('"""')
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from datetime import date, datetime, time")
        lines.append("from enum import Enum")
        lines.append("from typing import Any, Dict, List, Optional, Union")
        lines.append("from uuid import UUID")
        lines.append("")
        lines.append("from pydantic import BaseModel, ConfigDict, Field")
        lines.append("")
        lines.append("")

        sorted_entities = self.ast.topological_sort()
        non_enum_models: List[str] = []

        for ent_name in sorted_entities:
            entity = self.ast.get_entity(ent_name)
            if not entity:
                continue

            if entity.is_enum:
                lines.extend(self._generate_enum(entity))
            elif entity.is_union:
                lines.extend(self._generate_union(entity))
            else:
                lines.extend(self._generate_model(entity))
                non_enum_models.append(entity.name)

            lines.append("")
            lines.append("")

        # Model rebuild for forward references
        if non_enum_models:
            lines.append("# Resolve recursive and forward-referenced models")
            for model_name in non_enum_models:
                lines.append(f"{model_name}.model_rebuild()")
            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _generate_enum(self, entity: EntityAST) -> List[str]:
        """Generate Python Enum class."""
        lines: List[str] = []
        lines.append(f"class {entity.name}(str, Enum):")
        if self.include_docstrings and entity.description:
            lines.append(f'    """{entity.description}"""')
            lines.append("")

        for f in entity.fields:
            val = f.default_value if f.default_value is not None else f.name
            safe_name = re.sub(r"[^A-Za-z0-9_]", "_", f.name).upper()
            lines.append(f'    {safe_name} = "{val}"')

        return lines

    def _generate_union(self, entity: EntityAST) -> List[str]:
        """Generate Python Union type alias."""
        lines: List[str] = []
        if self.include_docstrings and entity.description:
            lines.append(f"# {entity.description}")
        types_str = ", ".join(entity.union_types) if entity.union_types else "Any"
        lines.append(f"{entity.name} = Union[{types_str}]")
        return lines

    def _generate_model(self, entity: EntityAST) -> List[str]:
        """Generate Pydantic BaseModel class."""
        lines: List[str] = []

        bases = entity.implements if entity.implements else ["BaseModel"]
        base_clause = ", ".join(bases)

        lines.append(f"class {entity.name}({base_clause}):")
        if self.include_docstrings and entity.description:
            lines.append(f'    """{entity.description}"""')
            lines.append("")

        if self.generate_orm_mode:
            lines.append(
                "    model_config = ConfigDict(from_attributes=True, populate_by_name=True)"
            )
            lines.append("")

        if not entity.fields:
            lines.append("    pass")
            return lines

        for f in entity.fields:
            type_str = self._map_py_type(f)
            field_args = self._build_field_args(f)

            if field_args:
                lines.append(f"    {f.name}: {type_str} = Field({', '.join(field_args)})")
            elif f.is_nullable:
                lines.append(f"    {f.name}: {type_str} = None")
            else:
                lines.append(f"    {f.name}: {type_str}")

        return lines

    def _build_field_args(self, f: FieldAST) -> List[str]:
        """Build arguments for pydantic.Field(...)."""
        args: List[str] = []

        if f.default_value is not None:
            if isinstance(f.default_value, str):
                args.append(f'default="{f.default_value}"')
            else:
                args.append(f"default={f.default_value}")
        elif f.is_nullable:
            args.append("default=None")
        elif f.is_array:
            args.append("default_factory=list")
        else:
            args.append("...")

        if self.include_docstrings and f.description:
            desc_escaped = f.description.replace('"', '\\"')
            args.append(f'description="{desc_escaped}"')

        for c in f.constraints:
            if c.type == ConstraintType.MIN_VALUE and "min" in c.parameters:
                args.append(f"ge={c.parameters['min']}")
            elif c.type == ConstraintType.MAX_VALUE and "max" in c.parameters:
                args.append(f"le={c.parameters['max']}")
            elif c.type == ConstraintType.MIN_LENGTH and "min_length" in c.parameters:
                args.append(f"min_length={c.parameters['min_length']}")
            elif c.type == ConstraintType.MAX_LENGTH and "max_length" in c.parameters:
                args.append(f"max_length={c.parameters['max_length']}")
            elif c.type == ConstraintType.PATTERN and "pattern" in c.parameters:
                args.append(f'pattern=r"{c.parameters["pattern"]}"')

        return args

    def _map_py_type(self, f: FieldAST) -> str:
        """Map field to Python / Pydantic type annotation."""
        base_type = ""
        if f.is_array:
            inner = f.array_item_target or (
                self._map_data_type(f.array_item_type) if f.array_item_type else "Any"
            )
            base_type = f"List[{inner}]"
        elif f.target_entity:
            base_type = f.target_entity
        elif f.enum_values:
            base_type = "str"
        else:
            base_type = self._map_data_type(f.type)

        if f.is_nullable:
            return f"Optional[{base_type}]"
        return base_type

    def _map_data_type(self, dt: DataType) -> str:
        """Map DataType to Python type name."""
        mapping = {
            DataType.STRING: "str",
            DataType.INTEGER: "int",
            DataType.BIGINT: "int",
            DataType.FLOAT: "float",
            DataType.DECIMAL: "float",
            DataType.BOOLEAN: "bool",
            DataType.DATETIME: "datetime",
            DataType.DATE: "date",
            DataType.TIME: "time",
            DataType.UUID: "UUID",
            DataType.JSON: "Dict[str, Any]",
            DataType.OBJECT: "Dict[str, Any]",
            DataType.BYTES: "bytes",
            DataType.ANY: "Any",
            DataType.NULL: "None",
        }
        return mapping.get(dt, "Any")


def transpile_to_pydantic(ast: SchemaAST, **kwargs: Any) -> str:
    """Convenience helper to transpile SchemaAST to Pydantic v2."""
    gen = PydanticGenerator(ast, **kwargs)
    return gen.generate()
