"""SQL DDL code generator converting SchemaAST into PostgreSQL, SQLite, or MySQL DDL.

Outputs tables, primary/foreign keys, enum types, indexes, comments, and constraints
with dependency-aware topological ordering using 100% Python standard library.
"""

from __future__ import annotations

import re
from typing import Any, List, Optional

from schema_illustrator_studio.models import (
    ConstraintType,
    DataType,
    EntityAST,
    FieldAST,
    RelationshipAST,
    SchemaAST,
)


class SQLGenerator:
    """Generates SQL DDL scripts from SchemaAST."""

    def __init__(
        self,
        ast: SchemaAST,
        dialect: str = "postgres",
        if_not_exists: bool = True,
        include_comments: bool = True,
        generate_fk_indexes: bool = True,
    ) -> None:
        self.ast = ast
        self.dialect = dialect.lower()
        self.if_not_exists = if_not_exists
        self.include_comments = include_comments
        self.generate_fk_indexes = generate_fk_indexes

    def generate(self) -> str:
        """Generate complete SQL DDL script."""
        lines: List[str] = []

        # Header
        lines.append("-- ========================================================")
        lines.append(f"-- Schema: {self.ast.name or 'Schema'}")
        if self.ast.description:
            lines.append(f"-- Description: {self.ast.description}")
        lines.append(f"-- Dialect: {self.dialect.upper()}")
        lines.append(f"-- Version: {self.ast.version}")
        lines.append("-- Generated by schema-illustrator-studio")
        lines.append("-- ========================================================")
        lines.append("")

        # 1. Generate ENUMs (PostgreSQL)
        if self.dialect in ("postgres", "postgresql"):
            for ent in self.ast.entities.values():
                if ent.is_enum:
                    vals = ", ".join(f"'{f.default_value or f.name}'" for f in ent.fields)
                    lines.append(f"CREATE TYPE {self._quote_id(ent.name)} AS ENUM ({vals});")
            lines.append("")

        # 2. Generate Tables in topological order
        sorted_names = self.ast.topological_sort()
        tables_to_create = [
            self.ast.get_entity(name)
            for name in sorted_names
            if self.ast.get_entity(name) and not self.ast.get_entity(name).is_enum and not self.ast.get_entity(name).is_union
        ]

        for ent in tables_to_create:
            if not ent:
                continue
            lines.extend(self._generate_table(ent))
            lines.append("")

        # 3. Generate Indexes
        if self.generate_fk_indexes:
            indexes = self._generate_indexes(tables_to_create)
            if indexes:
                lines.append("-- Indexes for Foreign Keys & Queries")
                lines.extend(indexes)
                lines.append("")

        # 4. Generate Comments (PostgreSQL)
        if self.include_comments and self.dialect in ("postgres", "postgresql"):
            comments = self._generate_comments(tables_to_create)
            if comments:
                lines.append("-- Table and Column Comments")
                lines.extend(comments)
                lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _quote_id(self, identifier: str) -> str:
        """Format SQL identifier."""
        clean = re.sub(r"[^A-Za-z0-9_]", "_", identifier)
        if self.dialect in ("postgres", "postgresql", "sqlite"):
            return f'"{clean}"'
        if self.dialect in ("mysql", "mariadb"):
            return f"`{clean}`"
        return clean

    def _generate_table(self, entity: EntityAST) -> List[str]:
        """Generate CREATE TABLE statement for an entity."""
        lines: List[str] = []
        if_clause = " IF NOT EXISTS" if self.if_not_exists else ""
        lines.append(f"CREATE TABLE{if_clause} {self._quote_id(entity.name)} (")

        col_lines: List[str] = []

        pks = entity.primary_keys()
        is_composite_pk = len(pks) > 1

        for f in entity.fields:
            col_def = f"  {self._quote_id(f.name)} {self._map_sql_type(f)}"

            if not f.is_nullable:
                col_def += " NOT NULL"

            if f.is_primary_key and not is_composite_pk:
                col_def += " PRIMARY KEY"

            if f.is_unique and not (f.is_primary_key and not is_composite_pk):
                col_def += " UNIQUE"

            if f.default_value is not None:
                def_val = f.default_value
                if isinstance(def_val, str) and not def_val.upper().startswith("CURRENT_") and not def_val.endswith("()"):
                    col_def += f" DEFAULT '{def_val}'"
                else:
                    col_def += f" DEFAULT {def_val}"

            col_lines.append(col_def)

        if is_composite_pk:
            pk_cols = ", ".join(self._quote_id(p.name) for p in pks)
            col_lines.append(f"  CONSTRAINT {self._quote_id(f'pk_{entity.name}')} PRIMARY KEY ({pk_cols})")

        for rel in self.ast.relationships:
            if rel.source_entity == entity.name:
                src_col = self._quote_id(rel.source_field)
                tgt_tbl = self._quote_id(rel.target_entity)
                tgt_col = self._quote_id(rel.target_field or "id")
                fk_name = self._quote_id(rel.name or f"fk_{entity.name}_{rel.source_field}")

                on_del = f" ON DELETE {rel.on_delete}" if rel.on_delete else ""
                on_upd = f" ON UPDATE {rel.on_update}" if rel.on_update else ""

                col_lines.append(
                    f"  CONSTRAINT {fk_name} FOREIGN KEY ({src_col}) REFERENCES {tgt_tbl}({tgt_col}){on_del}{on_upd}"
                )

        lines.append(",\n".join(col_lines))
        lines.append(");")
        return lines

    def _generate_indexes(self, tables: List[EntityAST]) -> List[str]:
        """Generate indexes for foreign key columns."""
        indexes: List[str] = []
        for rel in self.ast.relationships:
            idx_name = self._quote_id(f"idx_{rel.source_entity}_{rel.source_field}")
            src_tbl = self._quote_id(rel.source_entity)
            src_col = self._quote_id(rel.source_field)
            indexes.append(f"CREATE INDEX IF NOT EXISTS {idx_name} ON {src_tbl} ({src_col});")
        return indexes

    def _generate_comments(self, tables: List[EntityAST]) -> List[str]:
        """Generate PostgreSQL COMMENT ON statements."""
        comments: List[str] = []
        for ent in tables:
            if ent.description:
                desc = ent.description.replace("'", "''")
                comments.append(f"COMMENT ON TABLE {self._quote_id(ent.name)} IS '{desc}';")
            for f in ent.fields:
                if f.description:
                    f_desc = f.description.replace("'", "''")
                    comments.append(
                        f"COMMENT ON COLUMN {self._quote_id(ent.name)}.{self._quote_id(f.name)} IS '{f_desc}';"
                    )
        return comments

    def _map_sql_type(self, f: FieldAST) -> str:
        """Map FieldAST to SQL column data type."""
        target_ent = self.ast.get_entity(f.target_entity or "")
        if target_ent and target_ent.is_enum and self.dialect in ("postgres", "postgresql"):
            return self._quote_id(target_ent.name)

        if f.is_array:
            if self.dialect in ("postgres", "postgresql"):
                inner = self._map_single_type(f.array_item_type or DataType.STRING)
                return f"{inner}[]"
            return "JSON"

        return self._map_single_type(f.type)

    def _map_single_type(self, dt: DataType) -> str:
        """Map canonical DataType to SQL type."""
        if self.dialect in ("postgres", "postgresql"):
            mapping = {
                DataType.STRING: "VARCHAR(255)",
                DataType.INTEGER: "INTEGER",
                DataType.BIGINT: "BIGINT",
                DataType.FLOAT: "DOUBLE PRECISION",
                DataType.DECIMAL: "NUMERIC(12, 2)",
                DataType.BOOLEAN: "BOOLEAN",
                DataType.DATETIME: "TIMESTAMP WITH TIME ZONE",
                DataType.DATE: "DATE",
                DataType.TIME: "TIME WITHOUT TIME ZONE",
                DataType.UUID: "UUID",
                DataType.JSON: "JSONB",
                DataType.OBJECT: "JSONB",
                DataType.BYTES: "BYTEA",
                DataType.ANY: "TEXT",
                DataType.NULL: "TEXT",
            }
        elif self.dialect in ("mysql", "mariadb"):
            mapping = {
                DataType.STRING: "VARCHAR(255)",
                DataType.INTEGER: "INT",
                DataType.BIGINT: "BIGINT",
                DataType.FLOAT: "DOUBLE",
                DataType.DECIMAL: "DECIMAL(12, 2)",
                DataType.BOOLEAN: "TINYINT(1)",
                DataType.DATETIME: "DATETIME",
                DataType.DATE: "DATE",
                DataType.TIME: "TIME",
                DataType.UUID: "VARCHAR(36)",
                DataType.JSON: "JSON",
                DataType.OBJECT: "JSON",
                DataType.BYTES: "LONGBLOB",
                DataType.ANY: "LONGTEXT",
                DataType.NULL: "TEXT",
            }
        else:  # sqlite
            mapping = {
                DataType.STRING: "TEXT",
                DataType.INTEGER: "INTEGER",
                DataType.BIGINT: "INTEGER",
                DataType.FLOAT: "REAL",
                DataType.DECIMAL: "REAL",
                DataType.BOOLEAN: "INTEGER",
                DataType.DATETIME: "TEXT",
                DataType.DATE: "TEXT",
                DataType.TIME: "TEXT",
                DataType.UUID: "TEXT",
                DataType.JSON: "TEXT",
                DataType.OBJECT: "TEXT",
                DataType.BYTES: "BLOB",
                DataType.ANY: "TEXT",
                DataType.NULL: "TEXT",
            }

        return mapping.get(dt, "VARCHAR(255)")


def transpile_to_sql(ast: SchemaAST, **kwargs: Any) -> str:
    """Convenience helper to transpile SchemaAST to SQL DDL."""
    gen = SQLGenerator(ast, **kwargs)
    return gen.generate()
