"""TypeScript code generator converting SchemaAST into TypeScript interfaces, types, and enums.

Supports interface inheritance, JSDoc docstrings, Zod schema generation,
strict nullability, and clean type exports using 100% Python standard library.
"""

from __future__ import annotations

from typing import Any, List, Optional

from schema_illustrator_studio.models import DataType, EntityAST, FieldAST, SchemaAST


class TypeScriptGenerator:
    """Generates idiomatic TypeScript definitions from SchemaAST."""

    def __init__(
        self,
        ast: SchemaAST,
        use_interfaces: bool = True,
        export_types: bool = True,
        include_jsdoc: bool = True,
        strict_nulls: bool = True,
        generate_zod: bool = False,
    ) -> None:
        self.ast = ast
        self.use_interfaces = use_interfaces
        self.export_types = export_types
        self.include_jsdoc = include_jsdoc
        self.strict_nulls = strict_nulls
        self.generate_zod = generate_zod

    def generate(self) -> str:
        """Generate complete TypeScript file content."""
        lines: List[str] = []
        prefix = "export " if self.export_types else ""

        # Header
        lines.append("/**")
        lines.append(f" * Schema: {self.ast.name or 'Schema'}")
        if self.ast.description:
            lines.append(f" * {self.ast.description}")
        lines.append(f" * Version: {self.ast.version}")
        lines.append(" * Generated by schema-illustrator-studio")
        lines.append(" */")
        lines.append("")

        if self.generate_zod:
            lines.append('import { z } from "zod";')
            lines.append("")

        sorted_entities = self.ast.topological_sort()

        for ent_name in sorted_entities:
            entity = self.ast.get_entity(ent_name)
            if not entity:
                continue

            if entity.is_enum:
                lines.extend(self._generate_enum(entity, prefix))
            elif entity.is_union:
                lines.extend(self._generate_union(entity, prefix))
            else:
                lines.extend(self._generate_entity(entity, prefix))

            if self.generate_zod:
                lines.extend(self._generate_zod_schema(entity, prefix))

            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _generate_enum(self, entity: EntityAST, prefix: str) -> List[str]:
        """Generate TypeScript enum or string union."""
        lines: List[str] = []
        if self.include_jsdoc and entity.description:
            lines.append(f"/** {entity.description} */")

        lines.append(f"{prefix}enum {entity.name} {{")
        for f in entity.fields:
            val = f.default_value if f.default_value is not None else f.name
            lines.append(f'  {f.name} = "{val}",')
        lines.append("}")
        return lines

    def _generate_union(self, entity: EntityAST, prefix: str) -> List[str]:
        """Generate TypeScript union type alias."""
        lines: List[str] = []
        if self.include_jsdoc and entity.description:
            lines.append(f"/** {entity.description} */")

        union_str = " | ".join(entity.union_types) if entity.union_types else "unknown"
        lines.append(f"{prefix}type {entity.name} = {union_str};")
        return lines

    def _generate_entity(self, entity: EntityAST, prefix: str) -> List[str]:
        """Generate TypeScript interface or type alias."""
        lines: List[str] = []
        if self.include_jsdoc and entity.description:
            lines.append(f"/** {entity.description} */")

        extends_clause = ""
        if entity.implements:
            extends_clause = f" extends {', '.join(entity.implements)}"

        if self.use_interfaces and not entity.is_type_alias:
            lines.append(f"{prefix}interface {entity.name}{extends_clause} {{")
        else:
            intersection = f" & { ' & '.join(entity.implements)}" if entity.implements else ""
            lines.append(f"{prefix}type {entity.name} ={intersection} {{")

        for field in entity.fields:
            if self.include_jsdoc and field.description:
                lines.append(f"  /** {field.description} */")

            opt_mark = "?" if field.is_nullable else ""
            ts_type = self._map_field_type(field)

            if field.is_nullable and self.strict_nulls and not opt_mark:
                ts_type = f"{ts_type} | null"

            lines.append(f"  {field.name}{opt_mark}: {ts_type};")

        lines.append("}")
        return lines

    def _generate_zod_schema(self, entity: EntityAST, prefix: str) -> List[str]:
        """Generate Zod schema validation object."""
        lines: List[str] = []
        lines.append("")
        if entity.is_enum:
            values = [f'"{f.default_value or f.name}"' for f in entity.fields]
            lines.append(f"{prefix}const {entity.name}Schema = z.enum([{', '.join(values)}]);")
            return lines

        lines.append(f"{prefix}const {entity.name}Schema = z.object({{")
        for f in entity.fields:
            z_type = self._map_zod_type(f)
            if f.is_nullable:
                z_type += ".optional()"
            lines.append(f"  {f.name}: {z_type},")
        lines.append("});")
        return lines

    def _map_field_type(self, f: FieldAST) -> str:
        """Map FieldAST to TypeScript type string."""
        if f.is_array:
            inner = f.array_item_target or (
                self._map_data_type(f.array_item_type) if f.array_item_type else "unknown"
            )
            return f"{inner}[]"

        if f.target_entity:
            return f.target_entity

        if f.enum_values:
            return " | ".join(f'"{v}"' for v in f.enum_values)

        return self._map_data_type(f.type)

    def _map_data_type(self, dt: DataType) -> str:
        """Map canonical DataType to TypeScript scalar."""
        mapping = {
            DataType.STRING: "string",
            DataType.INTEGER: "number",
            DataType.BIGINT: "number",
            DataType.FLOAT: "number",
            DataType.DECIMAL: "number",
            DataType.BOOLEAN: "boolean",
            DataType.DATETIME: "Date",
            DataType.DATE: "string",
            DataType.TIME: "string",
            DataType.UUID: "string",
            DataType.JSON: "Record<string, unknown>",
            DataType.OBJECT: "Record<string, unknown>",
            DataType.BYTES: "Uint8Array",
            DataType.ANY: "any",
            DataType.NULL: "null",
        }
        return mapping.get(dt, "unknown")

    def _map_zod_type(self, f: FieldAST) -> str:
        """Map FieldAST to Zod validator string."""
        if f.is_array:
            inner_dt = f.array_item_type or DataType.STRING
            inner_z = self._map_zod_data_type(inner_dt)
            if f.array_item_target:
                inner_z = f"z.lazy(() => {f.array_item_target}Schema)"
            return f"z.array({inner_z})"

        if f.target_entity:
            return f"z.lazy(() => {f.target_entity}Schema)"

        if f.enum_values:
            vals = ", ".join(f'"{v}"' for v in f.enum_values)
            return f"z.enum([{vals}])"

        return self._map_zod_data_type(f.type)

    def _map_zod_data_type(self, dt: DataType) -> str:
        mapping = {
            DataType.STRING: "z.string()",
            DataType.INTEGER: "z.number().int()",
            DataType.BIGINT: "z.number().int()",
            DataType.FLOAT: "z.number()",
            DataType.DECIMAL: "z.number()",
            DataType.BOOLEAN: "z.boolean()",
            DataType.DATETIME: "z.date()",
            DataType.DATE: "z.string()",
            DataType.TIME: "z.string()",
            DataType.UUID: "z.string().uuid()",
            DataType.JSON: "z.record(z.unknown())",
            DataType.OBJECT: "z.record(z.unknown())",
            DataType.BYTES: "z.instanceof(Uint8Array)",
            DataType.ANY: "z.any()",
            DataType.NULL: "z.null()",
        }
        return mapping.get(dt, "z.unknown()")


def transpile_to_typescript(ast: SchemaAST, **kwargs: Any) -> str:
    """Convenience helper to transpile SchemaAST to TypeScript."""
    gen = TypeScriptGenerator(ast, **kwargs)
    return gen.generate()
